import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const registrySource = readFileSync(new URL('../lib/account/preview-registry.ts', import.meta.url), 'utf8')
const accountSource = readFileSync(new URL('../components/account/account-panel.tsx', import.meta.url), 'utf8')
const shellSource = readFileSync(new URL('../components/single-screen-preview/single-screen-preview-shell.tsx', import.meta.url), 'utf8')
const flowSource = readFileSync(new URL('../components/single-screen-preview/use-preview-flow.ts', import.meta.url), 'utf8')

test('preview registry stores verified previews by normalized email', () => {
  assert.equal(registrySource.includes('dottingo_preview_registry_v1'), true)
  assert.equal(registrySource.includes('normalizeRegistryEmail'), true)
  assert.equal(registrySource.includes('upsertAccountPreview'), true)
  assert.equal(registrySource.includes('isAccountPreviewSaved'), true)
  assert.equal(registrySource.includes('readAccountPreviews'), true)
  assert.equal(registrySource.includes('hideAccountPreview'), true)
})

test('account panel renders verified previews from projects with one card per project and size badges', () => {
  assert.equal(accountSource.includes('readAccountPreviews'), true)
  assert.equal(accountSource.includes('upsertAccountPreview'), true)
  assert.equal(registrySource.includes('sourceImageUrl: preview.sourceImageUrl ?? null'), true)
  assert.equal(accountSource.includes('identityProjectPreviewGroups'), true)
  assert.equal(accountSource.includes('dedupePreviewCardsBySize'), false)
  assert.equal(accountSource.includes('library.projects ?? []'), true)
  assert.equal(accountSource.includes('library.previews.map'), false)
  assert.equal(accountSource.includes('if (projectId) return `project:${projectId}`'), true)
  assert.equal(accountSource.includes('if (sourceGroupId && sourceGroupId !== projectId)'), true)
  assert.equal(accountSource.includes('if (sourceImageUrl) return `image:${sourceImageUrl}`'), true)
  assert.equal(accountSource.includes('previews[0].imageUrl'), false)
  assert.equal(accountSource.includes('record.sourceImageUrl || record.imageUrl'), false)
  assert.equal(accountSource.includes('preview.imageUrl'), false)
  assert.equal(accountSource.includes('aria-label={`Open ${previewBadgeLabel(record)} saved preview`}'), true)
  assert.equal(accountSource.includes('grid w-fit min-w-[3.7rem] grid-cols-1 gap-1'), true)
  assert.equal(accountSource.includes('h-5 items-center justify-center whitespace-nowrap rounded-full px-2 text-[10px]'), true)
  assert.equal(accountSource.includes('Saved design image'), true)
  assert.equal(accountSource.includes('h-20 w-20'), true)
  assert.equal(accountSource.includes('Open'), true)
  assert.equal(accountSource.includes('Open preview'), false)
  assert.equal(accountSource.includes('Continue checkout'), false)
  assert.equal(accountSource.includes('sizeAvailabilityLabel'), false)
  assert.equal(accountSource.includes('Source thumbnail saved'), false)
  assert.equal(accountSource.includes('Saved size only'), false)
  assert.equal(accountSource.includes('previewGroupsPerPage'), true)
  assert.equal(accountSource.includes('setPreviewPage'), true)
  assert.equal(accountSource.includes('Delete'), true)
  assert.equal(accountSource.includes('Hide'), false)
  assert.equal(accountSource.includes('Preview list comes next from MGE'), false)
})

test('account panel only renders saved size badges in history and deletes through MGE identity history', () => {
  assert.equal(accountSource.includes('FRAME_SIZE_OPTIONS'), false)
  assert.equal(accountSource.includes('attachVerifiedIdentityPreview'), true)
  assert.equal(accountSource.includes('sourceImageUrlFallback?: string | null'), true)
  assert.equal(accountSource.includes('attachedPreview?.sourceImageUrl ?? selectedPreview.sourceImageUrl ?? sourceImageUrlFallback ?? null'), true)
  assert.equal(accountSource.includes('attachedPreview?.sourceGroupId ?? selectedPreview.sourceGroupId ?? null'), true)
  assert.equal(accountSource.includes('createVerifiedIdentityProjectPreview'), false)
  assert.equal(accountSource.includes('handleGenerateProjectSize'), false)
  assert.equal(accountSource.includes('missingSizeOptions'), false)
  assert.equal(accountSource.includes('Generate ${option.label} saved preview'), false)
  assert.equal(accountSource.includes('deleteVerifiedIdentityProject'), true)
  assert.equal(accountSource.includes('deleteVerifiedIdentityPreview'), true)
  assert.equal(accountSource.includes('oldSameSizePreviewIds'), true)
  assert.equal(accountSource.includes('handleDeleteGroup'), true)
  assert.equal(accountSource.includes('onDeletedCurrentPreview'), true)
  assert.equal(accountSource.includes('deletedCurrentPreview'), true)
  assert.equal(accountSource.includes('sourceGroupId'), true)
  assert.equal(accountSource.includes('attached_to_mge_identity'), true)
  assert.equal(accountSource.includes('dedupePreviewCardsBySize'), false)
})

test('deleting the currently loaded account preview resets the main canvas and URL', () => {
  assert.equal(shellSource.includes('handleDeletedCurrentPreview'), true)
  assert.equal(shellSource.includes('actions.reset()'), true)
  assert.equal(shellSource.includes('url.searchParams.delete("preview_id")'), true)
  assert.equal(shellSource.includes('url.searchParams.delete("size_id")'), true)
  assert.equal(shellSource.includes('onDeletedCurrentPreview={handleDeletedCurrentPreview}'), true)
  assert.equal(shellSource.includes('account_current_preview_deleted_reset'), true)
})

test('account preview registry preserves source group ids independently from source image urls', () => {
  assert.equal(registrySource.includes('sourceImageUrl: preview.sourceImageUrl ?? null'), true)
  assert.equal(registrySource.includes('sourceGroupId: preview.sourceGroupId ?? null'), true)
  assert.equal(registrySource.includes('orientation: preview.orientation ?? null'), true)
  assert.equal(registrySource.includes('sourceGroupId: preview.sourceImageUrl ?? null'), false)
})

test('account panel treats the current preview size as saved from the canonical registry, not only stale component state', () => {
  assert.equal(accountSource.includes('isAccountPreviewSaved(identity.email, previewId, selectedSize?.id)'), true)
  assert.match(accountSource, /savedPreviews\.some\(\(record\) => record\.previewId === previewId && \(!selectedSize\?\.id \|\| record\.sizeId === selectedSize\.id\)\) \|\|\s*isAccountPreviewSaved\(identity\.email, previewId, selectedSize\?\.id\)/)
  assert.equal(accountSource.includes('Save current preview'), true)
})

test('preview shell registers the current ready preview when a global identity is verified', () => {
  assert.equal(shellSource.includes('upsertAccountPreview'), true)
  assert.equal(shellSource.includes('createSourceThumbnailDataUrl'), true)
  assert.equal(shellSource.includes('localSourceThumbnailUrl'), true)
  assert.equal(shellSource.includes('sourceImageUrl: attachedPreview?.sourceImageUrl ?? selectedPreview.sourceImageUrl ?? localSourceThumbnailUrl ?? null'), true)
  assert.equal(shellSource.includes('sourceGroupId: attachedPreview?.sourceGroupId ?? selectedPreview.sourceGroupId ?? activeIdentityProject?.sourceGroupId ?? null'), true)
  assert.equal(shellSource.includes('sourceImageUrlFallback={localSourceThumbnailUrl}'), true)
  assert.equal(shellSource.includes('isAccountPreviewSaved'), true)
  assert.equal(shellSource.includes('currentPreviewSaved'), true)
  assert.equal(shellSource.includes('selectedPreview.status !== "ready"'), true)
  assert.equal(shellSource.includes('account_preview_registered'), true)
})

test('saved preview links carry the saved size so reopened previews keep the correct canvas ratio', () => {
  assert.match(registrySource, /buildPreviewOpenPath\(previewId: string, sizeId\?: string \| null, orientation\?: FrameOrientation \| null\)/)
  assert.equal(registrySource.includes('params.set("size_id", sizeId)'), true)
  assert.equal(registrySource.includes('params.set("orientation", orientation)'), true)
  assert.equal(accountSource.includes('buildPreviewOpenPath(group.previews[0].previewId, group.previews[0].sizeId, group.previews[0].orientation)'), true)
  assert.equal(flowSource.includes('readPreviewSizeIdFromUrl'), true)
  assert.equal(flowSource.includes('normalizePreviewSizeIdFromUrl'), true)
  assert.equal(flowSource.includes('readPreviewOrientationFromUrl'), true)
  assert.equal(flowSource.includes('getFrameSizeOption(normalizedUrlSizeId)'), true)
})

test('saved preview URL size wins over stale local storage for the same preview id', () => {
  assert.equal(flowSource.includes('const normalizedUrlSizeId = normalizePreviewSizeIdFromUrl()'), true)
  assert.equal(flowSource.includes('const restoredMatchesUrlSize = !normalizedUrlSizeId || restored?.selectedSize?.id === normalizedUrlSizeId'), true)
  assert.equal(flowSource.includes('restoredMatchesUrlSize'), true)
})
